import { OnInit } from '@angular/core';
import { ConfigService } from 'tabby-core';
import { McpService } from '../services/mcpService';
import { McpLoggerService } from '../services/mcpLogger.service';
import { UrlOpeningService } from '../services/urlOpening.service';
/** @hidden */
export declare class McpSettingsTabComponent implements OnInit {
    config: ConfigService;
    private mcpService;
    private logger;
    private urlOpeningService;
    private bootstrapData;
    isLightMode: boolean;
    toggleTheme(): void;
    true: any;
    isServerRunning: boolean;
    serverUrl: string;
    port: number;
    enableDebugLogging: boolean;
    startOnBoot: boolean;
    instructionsVisible: boolean;
    stdioServerPath: string;
    vscodeSettingsJson: string;
    stdioSettingsJson: string;
    copyConfigJson(type: string): void;
    pairProgrammingEnabled: boolean;
    autoFocusTerminal: boolean;
    showConfirmationDialog: boolean;
    showResultDialog: boolean;
    constructor(config: ConfigService, mcpService: McpService, logger: McpLoggerService, urlOpeningService: UrlOpeningService, bootstrapData: any);
    ngOnInit(): void;
    private initializeConfig;
    private loadConfigValues;
    saveServerUrl(): void;
    savePort(): void;
    startServer(): Promise<void>;
    stopServer(): Promise<void>;
    private updateServerStatus;
    toggleDebugLogging(): void;
    toggleStartOnBoot(): void;
    togglePairProgrammingMode(): void;
    toggleAutoFocusTerminal(): void;
    toggleShowConfirmationDialog(): void;
    toggleShowResultDialog(): void;
    openGitHub(): void;
    openVSCodeExtension(): void;
    toggleInstructions(): void;
    private setStdioServerPath;
    private updateStdioConfigSnippet;
    private escapeJsonString;
    private pathExists;
    copyStdioPath(): void;
}
